In [46]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from geneview.gwas import qqplot

In [47]:
#df=pd.read_excel('horse_data.xls',na_values=['nan'])
pd.set_option('max_columns',30)
df=pd.read_excel('horse_data.xls')
print df.describe()

          surgery         Age  Hospital Number   rectal temperature  \
count  366.000000  368.000000      3.680000e+02          299.000000
mean     1.415301    1.608696      1.112334e+06           38.134448
std      0.493448    2.123985      1.560122e+06            0.711684
min      1.000000    1.000000      5.142790e+05           35.400000
25%      1.000000    1.000000      5.289152e+05           37.800000
50%      1.000000    1.000000      5.302990e+05           38.100000
75%      2.000000    1.000000      5.347275e+05           38.500000
max      2.000000    9.000000      5.305629e+06           40.800000

            pulse  respiratory rate  temperature of extremities  \
count  342.000000        297.000000                  303.000000
mean    70.757310         30.521886                    2.356436
std     28.089867         17.669651                    1.041371
min     30.000000          8.000000                    1.000000
25%     48.000000         18.000000                    1.000000
50%     60.000000         28.000000                    3.000000
75%     88.000000         36.000000                    3.000000
max    184.000000         96.000000                    4.000000

       peripheral pulse  mucous membranes  capillary refill time        pain  \
count        285.000000        320.000000             330.000000  305.000000
mean           1.961404          2.834375               1.303030    2.908197
std            1.052454          1.591732               0.473289    1.304634
min            1.000000          1.000000               1.000000    1.000000
25%            1.000000          1.000000               1.000000    2.000000
50%            1.000000          3.000000               1.000000    3.000000
75%            3.000000          4.000000               2.000000    4.000000
max            4.000000          6.000000               3.000000    5.000000

       peristalsis  abdominal distension  nasogastric tube  \
count   316.000000            303.000000        237.000000
mean      2.908228              2.224422          1.738397
std       0.986156              1.059081          0.650230
min       1.000000              1.000000          1.000000
25%       3.000000              1.000000          1.000000
50%       3.000000              2.000000          2.000000
75%       4.000000              3.000000          2.000000
max       4.000000              4.000000          3.000000

       nasogastric reflux  nasogastric reflux PH  rectal examination - feces  \
count          235.000000              69.000000                  240.000000
mean             1.608511               4.962319                    2.779167
std              0.811201               2.003901                    1.246410
min              1.000000               1.000000                    1.000000
25%              1.000000               3.500000                    1.000000
50%              1.000000               5.400000                    3.000000
75%              2.000000               6.500000                    4.000000
max              3.000000               8.500000                    4.000000

          abdomen   packed cell volume  total protein  \
count  225.000000           331.000000     325.000000
mean     3.715556            45.656798      24.771077
std      1.451286            10.865663      27.704880
min      1.000000             4.000000       3.300000
25%      3.000000            37.250000       6.500000
50%      4.000000            44.000000       7.500000
75%      5.000000            52.000000      58.000000
max      5.000000            75.000000      89.000000

       abdominocentesis appearance  abdomcentesis total protein     outcome  \
count                   174.000000                   133.000000  366.000000
mean                      2.045977                     2.948120    1.527322
std                       0.803289                     1.927064    0.731347
min                       1.000000                     0.100000    1.000000
25%                       1.000000                     2.000000    1.000000
50%                       2.000000                     2.100000    1.000000
75%                       3.000000                     3.900000    2.000000
max                       3.000000                    10.100000    3.000000

       surgical lesion   type of lesion  Unnamed: 25  Unnamed: 26    cp_ data
count       368.000000       368.000000   368.000000   368.000000  368.000000
mean          1.369565      3650.834239    96.972826     6.002717    1.663043
std           0.483344      5360.219154   640.506258   115.152085    0.473313
min           1.000000         0.000000     0.000000     0.000000    1.000000
25%           1.000000      2111.750000     0.000000     0.000000    1.000000
50%           1.000000      3025.000000     0.000000     0.000000    2.000000
75%           2.000000      3209.000000     0.000000     0.000000    2.000000
max           2.000000     41110.000000  7111.000000  2209.000000    2.000000

In [48]:
print df['respiratory rate'].value_counts()

20.0    35
24.0    30
12.0    27
16.0    26
30.0    26
40.0    22
36.0    20
28.0    16
32.0    12
18.0    10
60.0    10
48.0     6
44.0     5
14.0     4
10.0     4
96.0     3
35.0     3
68.0     3
80.0     3
42.0     3
84.0     2
70.0     2
21.0     2
90.0     2
72.0     2
22.0     2
51.0     2
9.0      2
50.0     2
23.0     1
15.0     1
34.0     1
25.0     1
8.0      1
52.0     1
58.0     1
13.0     1
66.0     1
26.0     1
88.0     1
Name: respiratory rate, dtype: int64

In [49]:
df.index

RangeIndex(start=0, stop=368, step=1)

In [50]:
a=df['respiratory rate'].value_counts()
#print a
print a.keys()[0]

20.0

In [51]:
print df['surgery'].value_counts()

1.0    214
2.0    152
Name: surgery, dtype: int64

In [52]:
print df['temperature of extremities'].value_counts()

3.0    135
1.0     95
2.0     39
4.0     34
Name: temperature of extremities, dtype: int64

In [53]:
print df['capillary refill time'].value_counts()

1.0    232
2.0     96
3.0      2
Name: capillary refill time, dtype: int64

In [54]:
print df['pain'].value_counts()

3.0    82
2.0    77
5.0    50
1.0    49
4.0    47
Name: pain, dtype: int64

In [55]:
print df['peristalsis'].value_counts()

1.0    98
3.0    81
4.0    50
2.0    38
5.0    28
6.0    25
Name: mucous membranes, dtype: int64

In [57]:
print df['abdominal distension'].value_counts()

1.0    101
3.0     85
2.0     75
4.0     42
Name: abdominal distension, dtype: int64

In [58]:
print df['nasogastric tube'].value_counts()

2.0    121
1.0     89
3.0     27
Name: nasogastric tube, dtype: int64

In [59]:
print df['nasogastric reflux'].value_counts()

1.0    141
3.0     49
2.0     45
Name: nasogastric reflux, dtype: int64

In [62]:
print df['rectal examination - feces'].value_counts()

4.0    97
1.0    68
3.0    61
2.0    14
Name: rectal examination - feces, dtype: int64

In [63]:
print df['abdomen'].value_counts()

5.0    96
4.0    55
1.0    31
2.0    24
3.0    19
Name: abdomen, dtype: int64

In [64]:
print df['abdominocentesis appearance'].value_counts()

2.0    62
3.0    60
1.0    52
Name: abdominocentesis appearance, dtype: int64

In [65]:
print df['outcome'].value_counts()

1.0    225
2.0     89
3.0     52
Name: outcome, dtype: int64

In [66]:
print df['surgical lesion'].value_counts()

1    232
2    136
Name: surgical lesion, dtype: int64

In [67]:
print df['cp_ data'].value_counts()

2    244
1    124
Name: cp_ data, dtype: int64

In [61]:
df.columns

Index([                    u'surgery',                         u'Age',
                  u'Hospital Number ',          u'rectal temperature',
                             u'pulse',            u'respiratory rate',
        u'temperature of extremities',            u'peripheral pulse',
                  u'mucous membranes',       u'capillary refill time',
                              u'pain',                 u'peristalsis',
              u'abdominal distension',            u'nasogastric tube',
                u'nasogastric reflux',       u'nasogastric reflux PH',
        u'rectal examination - feces',                     u'abdomen',
               u' packed cell volume',               u'total protein',
       u'abdominocentesis appearance', u'abdomcentesis total protein',
                           u'outcome',             u'surgical lesion',
                   u' type of lesion',                 u'Unnamed: 25',
                       u'Unnamed: 26',                    u'cp_ data'],
      dtype='object')

In [68]:
df.describe()['rectal temperature']

count    299.000000
mean      38.134448
std        0.711684
min       35.400000
25%       37.800000
50%       38.100000
75%       38.500000
max       40.800000
Name: rectal temperature, dtype: float64

In [69]:
df.describe()['pulse']

count    342.000000
mean      70.757310
std       28.089867
min       30.000000
25%       48.000000
50%       60.000000
75%       88.000000
max      184.000000
Name: pulse, dtype: float64

In [70]:
df.describe()['respiratory rate']

count    297.000000
mean      30.521886
std       17.669651
min        8.000000
25%       18.000000
50%       28.000000
75%       36.000000
max       96.000000
Name: respiratory rate, dtype: float64

In [71]:
df.describe()['nasogastric reflux PH']

count    69.000000
mean      4.962319
std       2.003901
min       1.000000
25%       3.500000
50%       5.400000
75%       6.500000
max       8.500000
Name: nasogastric reflux PH, dtype: float64

In [73]:
df.describe()[' packed cell volume']

count    331.000000
mean      45.656798
std       10.865663
min        4.000000
25%       37.250000
50%       44.000000
75%       52.000000
max       75.000000
Name:  packed cell volume, dtype: float64

In [74]:
df.describe()['total protein']

count    325.000000
mean      24.771077
std       27.704880
min        3.300000
25%        6.500000
50%        7.500000
75%       58.000000
max       89.000000
Name: total protein, dtype: float64

In [75]:
df.describe()['abdomcentesis total protein']

count    133.000000
mean       2.948120
std        1.927064
min        0.100000
25%        2.000000
50%        2.100000
75%        3.900000
max       10.100000
Name: abdomcentesis total protein, dtype: float64

In [78]:
print df['rectal temperature'].value_counts()

38.0    34
38.3    23
38.2    23
37.8    21
38.5    21
37.5    16
38.1    15
38.4    14
38.6    14
37.6    10
37.7    10
37.9     9
38.7     9
37.2     7
37.3     6
39.0     6
38.8     6
39.2     5
37.1     5
37.0     4
39.3     4
39.5     4
38.9     4
37.4     4
39.1     3
39.4     3
36.5     2
36.0     2
39.7     2
36.6     2
40.3     2
39.9     1
35.4     1
40.0     1
36.9     1
39.6     1
36.4     1
36.8     1
40.8     1
36.1     1
Name: rectal temperature, dtype: int64

In [79]:
print df['pulse'].value_counts()

48.0     35
60.0     33
40.0     21
44.0     16
88.0     15
42.0     15
52.0     14
72.0     13
100.0    13
120.0    12
84.0     11
80.0     11
54.0      9
56.0      9
96.0      8
64.0      8
66.0      7
50.0      6
104.0     5
68.0      5
92.0      5
76.0      5
78.0      5
70.0      4
45.0      4
90.0      4
36.0      4
150.0     3
86.0      3
112.0     3
108.0     3
114.0     3
140.0     3
30.0      2
82.0      2
65.0      2
130.0     2
75.0      2
124.0     2
164.0     1
98.0      1
184.0     1
38.0      1
49.0      1
146.0     1
160.0     1
132.0     1
46.0      1
129.0     1
128.0     1
55.0      1
110.0     1
136.0     1
34.0      1
Name: pulse, dtype: int64

In [80]:
print df['respiratory rate'].value_counts()

20.0    35
24.0    30
12.0    27
16.0    26
30.0    26
40.0    22
36.0    20
28.0    16
32.0    12
18.0    10
60.0    10
48.0     6
44.0     5
14.0     4
10.0     4
96.0     3
35.0     3
68.0     3
80.0     3
42.0     3
84.0     2
70.0     2
21.0     2
90.0     2
72.0     2
22.0     2
51.0     2
9.0      2
50.0     2
23.0     1
15.0     1
34.0     1
25.0     1
8.0      1
52.0     1
58.0     1
13.0     1
66.0     1
26.0     1
88.0     1
Name: respiratory rate, dtype: int64

In [81]:
print df['nasogastric reflux PH'].value_counts()

2.0    10
7.0     9
5.0     7
6.5     6
5.5     4
6.0     4
3.0     3
4.5     3
4.0     3
7.5     3
1.5     2
1.0     2
7.2     2
8.5     1
3.5     1
5.3     1
8.0     1
4.3     1
5.8     1
6.2     1
4.4     1
5.4     1
5.9     1
5.7     1
Name: nasogastric reflux PH, dtype: int64

In [82]:
print df[' packed cell volume'].value_counts()

37.0    22
45.0    17
44.0    17
43.0    17
50.0    16
35.0    16
40.0    14
36.0    13
47.0    13
48.0    11
42.0    11
33.0    10
38.0    10
41.0    10
39.0     9
60.0     9
46.0     9
54.0     8
52.0     7
49.0     7
55.0     6
57.0     6
65.0     6
53.0     6
64.0     5
34.0     5
68.0     4
59.0     4
32.0     4
30.0     3
58.0     3
66.0     3
73.0     2
74.0     2
51.0     2
31.0     2
56.0     2
63.0     2
75.0     2
69.0     2
31.5     1
4.0      1
62.0     1
28.0     1
37.5     1
72.0     1
71.0     1
67.0     1
26.0     1
24.0     1
27.0     1
23.0     1
70.0     1
6.4      1
Name:  packed cell volume, dtype: int64

In [83]:
print df['total protein'].value_counts()

7.5     17
6.5     16
7.0     15
6.6     12
6.0     11
5.9     10
65.0    10
6.8      9
7.2      9
6.7      9
6.2      8
8.5      7
70.0     7
6.3      7
6.4      6
5.8      6
8.0      6
6.1      6
75.0     5
7.7      5
5.7      5
64.0     5
56.0     5
7.6      5
69.0     5
7.8      4
61.0     4
67.0     4
8.6      4
5.5      4
        ..
8.7      2
8.2      2
7.1      2
81.0     2
4.9      2
82.0     1
8.8      1
11.0     1
86.0     1
46.0     1
7.9      1
9.1      1
3.3      1
4.6      1
10.2     1
4.7      1
79.0     1
36.0     1
3.5      1
5.0      1
9.0      1
13.0     1
50.0     1
8.9      1
4.0      1
51.0     1
89.0     1
59.0     1
53.0     1
85.0     1
Name: total protein, dtype: int64

In [84]:
print df['abdomcentesis total protein'].value_counts()

2.0     33
1.0     21
3.9      5
5.0      4
2.8      4
2.6      4
3.6      3
4.3      3
3.4      3
7.0      3
1.4      3
1.1      2
2.5      2
2.1      2
8.0      2
3.1      2
2.2      2
4.5      2
2.3      2
5.3      2
3.0      2
4.6      2
1.6      2
6.0      2
4.1      2
1.5      1
10.0     1
6.5      1
0.9      1
4.4      1
2.9      1
1.3      1
4.8      1
5.2      1
5.7      1
6.6      1
3.3      1
7.4      1
0.1      1
4.7      1
3.7      1
10.1     1
3.2      1
1.8      1
Name: abdomcentesis total protein, dtype: int64

In [92]:
df.fillna({3:38.0,4:48,5:20.0,15:2.0,18:37.0,19:7.5,21:2.0},inplace=True)

,surgery,Age,Hospital Number,rectal temperature,pulse,respiratory rate,temperature of extremities,peripheral pulse,mucous membranes,capillary refill time,pain,peristalsis,abdominal distension,nasogastric tube,nasogastric reflux,nasogastric reflux PH,rectal examination - feces,abdomen,packed cell volume,total protein,abdominocentesis appearance,abdomcentesis total protein,outcome,surgical lesion,type of lesion,Unnamed: 25,Unnamed: 26,cp_ data
0,2.0,1,530101,38.5,66.0,28.0,3.0,3.0,NaN,2.0,5.0,4.0,4.0,NaN,NaN,NaN,3.0,5.0,45.0,8.4,NaN,NaN,2.0,2,11300,0,0,2
1,1.0,1,534817,39.2,88.0,20.0,NaN,NaN,4.0,1.0,3.0,4.0,2.0,NaN,NaN,NaN,4.0,2.0,50.0,85.0,2.0,2.0,3.0,2,2208,0,0,2
2,2.0,1,530334,38.3,40.0,24.0,1.0,1.0,3.0,1.0,3.0,3.0,1.0,NaN,NaN,NaN,1.0,1.0,33.0,6.7,NaN,NaN,1.0,2,0,0,0,1
3,1.0,9,5290409,39.1,164.0,84.0,4.0,1.0,6.0,2.0,2.0,4.0,4.0,1.0,2.0,5.0,3.0,NaN,48.0,7.2,3.0,5.3,2.0,1,2208,0,0,1
4,2.0,1,530255,37.3,104.0,35.0,NaN,NaN,6.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,74.0,7.4,NaN,NaN,2.0,2,4300,0,0,2
5,2.0,1,528355,NaN,NaN,NaN,2.0,1.0,3.0,1.0,2.0,3.0,2.0,2.0,1.0,NaN,3.0,3.0,NaN,NaN,NaN,NaN,1.0,2,0,0,0,2
6,1.0,1,526802,37.9,48.0,16.0,1.0,1.0,1.0,1.0,3.0,3.0,3.0,1.0,1.0,NaN,3.0,5.0,37.0,7.0,NaN,NaN,1.0,1,3124,0,0,2
7,1.0,1,529607,NaN,60.0,NaN,3.0,NaN,NaN,1.0,NaN,4.0,2.0,2.0,1.0,NaN,3.0,4.0,44.0,8.3,NaN,NaN,2.0,1,2208,0,0,2
8,2.0,1,530051,NaN,80.0,36.0,3.0,4.0,3.0,1.0,4.0,4.0,4.0,2.0,1.0,NaN,3.0,5.0,38.0,6.2,NaN,NaN,3.0,1,3205,0,0,2
9,2.0,9,5299629,38.3,90.0,NaN,1.0,NaN,1.0,1.0,5.0,3.0,1.0,2.0,1.0,NaN,3.0,NaN,40.0,6.2,1.0,2.2,1.0,2,0,0,0,1
10,1.0,1,528548,38.1,66.0,12.0,3.0,3.0,5.0,1.0,3.0,3.0,1.0,2.0,1.0,3.0,2.0,5.0,44.0,6.0,2.0,3.6,1.0,1,2124,0,0,1
11,2.0,1,527927,39.1,72.0,52.0,2.0,NaN,2.0,1.0,2.0,1.0,2.0,1.0,1.0,NaN,4.0,4.0,50.0,7.8,NaN,NaN,1.0,1,2111,0,0,2
12,1.0,1,528031,37.2,42.0,12.0,2.0,1.0,1.0,1.0,3.0,3.0,3.0,3.0,1.0,NaN,4.0,5.0,NaN,7.0,NaN,NaN,1.0,2,4124,0,0,2
13,2.0,9,5291329,38.0,92.0,28.0,1.0,1.0,2.0,1.0,1.0,3.0,2.0,3.0,NaN,7.2,1.0,1.0,37.0,6.1,1.0,NaN,2.0,2,0,0,0,1
14,1.0,1,534917,38.2,76.0,28.0,3.0,1.0,1.0,1.0,3.0,4.0,1.0,2.0,2.0,NaN,4.0,4.0,46.0,81.0,1.0,2.0,1.0,1,2112,0,0,2
15,1.0,1,530233,37.6,96.0,48.0,3.0,1.0,4.0,1.0,5.0,3.0,3.0,2.0,3.0,4.5,4.0,NaN,45.0,6.8,NaN,NaN,2.0,1,3207,0,0,2
16,1.0,9,5301219,NaN,128.0,36.0,3.0,3.0,4.0,2.0,4.0,4.0,3.0,3.0,NaN,NaN,4.0,5.0,53.0,7.8,3.0,4.7,2.0,2,1400,0,0,1
17,2.0,1,526639,37.5,48.0,24.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,2,0,0,0,2
18,1.0,1,5290481,37.6,64.0,21.0,1.0,1.0,2.0,1.0,2.0,3.0,1.0,1.0,1.0,NaN,2.0,5.0,40.0,7.0,1.0,NaN,1.0,1,4205,0,0,1
19,2.0,1,532110,39.4,110.0,35.0,4.0,3.0,6.0,NaN,NaN,3.0,3.0,NaN,NaN,NaN,NaN,NaN,55.0,8.7,NaN,NaN,1.0,2,0,0,0,2
20,1.0,1,530157,39.9,72.0,60.0,1.0,1.0,5.0,2.0,5.0,4.0,4.0,3.0,1.0,NaN,4.0,4.0,46.0,6.1,2.0,NaN,1.0,1,2111,0,0,2
21,2.0,1,529340,38.4,48.0,16.0,1.0,NaN,1.0,1.0,1.0,3.0,1.0,2.0,3.0,5.5,4.0,3.0,49.0,6.8,NaN,NaN,1.0,2,0,0,0,2
22,1.0,1,521681,38.6,42.0,34.0,2.0,1.0,4.0,NaN,2.0,3.0,1.0,NaN,NaN,NaN,1.0,NaN,48.0,7.2,NaN,NaN,1.0,1,3111,0,0,2
23,1.0,9,534998,38.3,130.0,60.0,NaN,3.0,NaN,1.0,2.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,50.0,70.0,NaN,NaN,1.0,1,3111,0,0,2
24,1.0,1,533692,38.1,60.0,12.0,3.0,3.0,3.0,1.0,NaN,4.0,3.0,3.0,2.0,2.0,NaN,NaN,51.0,65.0,NaN,NaN,1.0,1,3111,0,0,2
25,2.0,1,529518,37.8,60.0,42.0,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,2,0,0,0,2
26,1.0,1,530526,38.3,72.0,30.0,4.0,3.0,3.0,2.0,3.0,3.0,3.0,2.0,1.0,NaN,3.0,5.0,43.0,7.0,2.0,3.9,1.0,1,3111,0,0,1
27,1.0,1,528653,37.8,48.0,12.0,3.0,1.0,1.0,1.0,NaN,3.0,2.0,1.0,1.0,NaN,1.0,3.0,37.0,5.5,2.0,1.3,1.0,2,4122,0,0,1
28,1.0,1,5279442,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2,4300,0,0,2
29,2.0,1,535415,37.7,48.0,NaN,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,NaN,NaN,NaN,45.0,76.0,NaN,NaN,1.0,2,0,0,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
338,2.0,1,530695,37.5,44.0,NaN,1.0,1.0,1.0,1.0,3.0,3.0,2.0,NaN,NaN,NaN,NaN,NaN,45.0,5.8,2.0,1.4,1.0,2,3111,0,0,1
339,2.0,1,533889,38.2,42.0,16.0,1.0,1.0,3.0,1.0,1.0,3.0,1.0,NaN,NaN,NaN,1.0,NaN,35.0,60.0,1.0,1.0,1.0,2,0,0,0,2
340,2.0,1,533815,38.0,56.0,44.0,3.0,3.0,3.0,NaN,NaN,1.0,1.0,2.0,1.0,NaN,4.0,NaN,47.0,70.0,2.0,1.0,1.0,2,0,0,0,2
341,2.0,1,527664,38.3,45.0,20.0,3.0,3.0,2.0,2.0,2.0,4.0,1.0,2.0,NaN,NaN,4.0,NaN,NaN,NaN,NaN,NaN,1.0,2,0,0,0,2
342,1.0,1,5262542,NaN,48.0,96.0,1.0,1.0,3.0,1.0,NaN,4.0,1.0,2.0,1.0,NaN,1.0,4.0,42.0,8.0,1.0,NaN,1.0,1,2208,0,0,2
343,1.0,1,528268,37.7,55.0,28.0,2.0,1.0,2.0,1.0,2.0,3.0,3.0,NaN,3.0,5.0,4.0,5.0,NaN,NaN,NaN,NaN,1.0,1,3209,0,0,2
344,2.0,1,528919,36.0,100.0,20.0,4.0,3.0,6.0,2.0,2.0,4.0,3.0,1.0,1.0,NaN,4.0,5.0,74.0,5.7,2.0,2.5,3.0,1,3205,0,0,1
345,1.0,1,527494,37.1,60.0,20.0,2.0,NaN,4.0,1.0,3.0,NaN,3.0,NaN,2.0,5.0,3.0,4.0,64.0,8.5,2.0,NaN,1.0,1,7111,0,0,1
346,2.0,1,529980,37.1,114.0,40.0,3.0,NaN,3.0,2.0,2.0,2.0,1.0,NaN,NaN,NaN,NaN,3.0,32.0,NaN,3.0,6.5,1.0,2,400,0,0,2
347,1.0,1,533954,38.1,72.0,30.0,3.0,3.0,3.0,1.0,4.0,4.0,3.0,2.0,1.0,NaN,3.0,5.0,37.0,56.0,3.0,1.0,1.0,1,4206,0,0,2
348,1.0,1,5281092,37.0,44.0,12.0,3.0,1.0,1.0,2.0,1.0,1.0,1.0,NaN,NaN,NaN,4.0,2.0,40.0,6.7,3.0,8.0,1.0,1,2208,0,0,2
349,1.0,1,534686,38.6,48.0,20.0,3.0,1.0,1.0,1.0,4.0,3.0,1.0,NaN,NaN,NaN,3.0,NaN,37.0,75.0,NaN,NaN,1.0,1,3111,0,0,2
350,1.0,1,534475,NaN,82.0,72.0,3.0,1.0,4.0,1.0,2.0,3.0,3.0,NaN,3.0,NaN,4.0,4.0,53.0,65.0,3.0,2.0,3.0,1,2209,3205,0,2
351,1.0,9,5274919,38.2,78.0,60.0,4.0,4.0,6.0,NaN,3.0,3.0,3.0,NaN,NaN,NaN,1.0,NaN,59.0,5.8,3.0,3.1,2.0,1,1400,0,0,1
352,2.0,1,533815,37.8,60.0,16.0,1.0,1.0,3.0,1.0,2.0,3.0,2.0,1.0,2.0,NaN,3.0,NaN,41.0,73.0,NaN,NaN,3.0,2,4124,0,0,2
353,1.0,1,534156,38.7,34.0,30.0,2.0,NaN,3.0,1.0,2.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,33.0,69.0,NaN,2.0,3.0,1,7113,0,0,2
354,1.0,1,514279,NaN,36.0,12.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,NaN,1.0,5.0,44.0,NaN,NaN,NaN,1.0,1,31110,0,0,1
355,2.0,1,528433,38.3,44.0,60.0,NaN,NaN,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.4,36.0,NaN,NaN,1.0,1,0,0,0,2
356,2.0,1,527465,37.4,54.0,18.0,3.0,NaN,1.0,1.0,3.0,4.0,3.0,2.0,2.0,NaN,4.0,5.0,30.0,7.1,2.0,NaN,1.0,1,7111,0,0,1
357,1.0,1,534268,NaN,NaN,NaN,4.0,3.0,NaN,2.0,2.0,4.0,1.0,NaN,NaN,NaN,NaN,NaN,54.0,76.0,3.0,2.0,1.0,1,8405,0,0,2
358,1.0,1,535337,36.6,48.0,16.0,3.0,1.0,3.0,1.0,4.0,1.0,1.0,1.0,1.0,NaN,NaN,NaN,27.0,56.0,NaN,NaN,3.0,1,4206,0,0,2
359,1.0,1,534111,38.5,90.0,NaN,1.0,1.0,3.0,1.0,3.0,3.0,3.0,2.0,3.0,2.0,4.0,5.0,47.0,79.0,NaN,NaN,1.0,1,6112,0,0,2
360,1.0,1,530576,NaN,75.0,12.0,1.0,1.0,4.0,1.0,5.0,3.0,3.0,NaN,3.0,5.8,NaN,NaN,58.0,8.5,1.0,NaN,1.0,1,2209,0,0,1
361,2.0,1,529930,38.2,42.0,NaN,3.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,1.0,NaN,3.0,2.0,35.0,5.9,2.0,NaN,1.0,2,3113,0,0,2
362,1.0,9,5274919,38.2,78.0,60.0,4.0,4.0,6.0,NaN,3.0,3.0,3.0,NaN,NaN,NaN,1.0,NaN,59.0,5.8,3.0,3.1,2.0,1,2205,0,0,1
363,2.0,1,529695,38.6,60.0,30.0,1.0,1.0,3.0,1.0,4.0,2.0,2.0,1.0,1.0,NaN,NaN,NaN,40.0,6.0,1.0,NaN,1.0,1,3205,0,0,2
364,2.0,1,528452,37.8,42.0,40.0,1.0,1.0,1.0,1.0,1.0,3.0,1.0,NaN,NaN,NaN,3.0,3.0,36.0,6.2,NaN,NaN,1.0,2,4124,0,0,2
365,1.0,1,534783,38.0,60.0,12.0,1.0,1.0,2.0,1.0,2.0,1.0,1.0,1.0,1.0,NaN,1.0,4.0,44.0,65.0,3.0,2.0,3.0,1,2209,0,0,2
366,2.0,1,528926,38.0,42.0,12.0,3.0,NaN,3.0,1.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,1.0,37.0,5.8,NaN,NaN,1.0,2,3111,0,0,2
367,2.0,1,530670,37.6,88.0,36.0,3.0,1.0,1.0,1.0,3.0,3.0,2.0,1.0,3.0,1.5,NaN,NaN,44.0,6.0,NaN,NaN,2.0,1,2112,0,0,2

In [91]:
df.columns

Index([                    u'surgery',                         u'Age',
                  u'Hospital Number ',          u'rectal temperature',
                             u'pulse',            u'respiratory rate',
        u'temperature of extremities',            u'peripheral pulse',
                  u'mucous membranes',       u'capillary refill time',
                              u'pain',                 u'peristalsis',
              u'abdominal distension',            u'nasogastric tube',
                u'nasogastric reflux',       u'nasogastric reflux PH',
        u'rectal examination - feces',                     u'abdomen',
               u' packed cell volume',               u'total protein',
       u'abdominocentesis appearance', u'abdomcentesis total protein',
                           u'outcome',             u'surgical lesion',
                   u' type of lesion',                 u'Unnamed: 25',
                       u'Unnamed: 26',                    u'cp_ data'],
      dtype='object')

In [93]:
df['rectal temperature'].fillna(38.0, inplace=True)

In [95]:
df['pulse'].fillna(48, inplace=True)
df['respiratory rate'].fillna(20.0, inplace=True)
df['nasogastric reflux PH'].fillna(2.0, inplace=True)
df[' packed cell volume'].fillna(37.0, inplace=True)
df['total protein'].fillna(7.5, inplace=True)
df['abdomcentesis total protein'].fillna(2.0, inplace=True)

In [96]:
df.describe()

,surgery,Age,Hospital Number,rectal temperature,pulse,respiratory rate,temperature of extremities,peripheral pulse,mucous membranes,capillary refill time,pain,peristalsis,abdominal distension,nasogastric tube,nasogastric reflux,nasogastric reflux PH,rectal examination - feces,abdomen,packed cell volume,total protein,abdominocentesis appearance,abdomcentesis total protein,outcome,surgical lesion,type of lesion,Unnamed: 25,Unnamed: 26,cp_ data
count,366.000000,368.000000,3.680000e+02,368.000000,368.000000,368.000000,303.000000,285.000000,320.000000,330.000000,305.000000,316.000000,303.000000,237.000000,235.000000,368.000000,240.000000,225.000000,368.000000,368.000000,174.000000,368.000000,366.000000,368.000000,368.000000,368.000000,368.000000,368.000000
mean,1.415301,1.608696,1.112334e+06,38.109239,69.149457,28.491848,2.356436,1.961404,2.834375,1.303030,2.908197,2.908228,2.224422,1.738397,1.608511,2.555435,2.779167,3.715556,44.786413,22.752989,2.045977,2.342663,1.527322,1.369565,3650.834239,96.972826,6.002717,1.663043
std,0.493448,2.123985,1.560122e+06,0.643451,27.699083,16.404291,1.041371,1.052454,1.591732,0.473289,1.304634,0.986156,1.059081,0.650230,0.811201,1.443796,1.246410,1.451286,10.628053,26.617551,0.803289,1.242460,0.731347,0.483344,5360.219154,640.506258,115.152085,0.473313
min,1.000000,1.000000,5.142790e+05,35.400000,30.000000,8.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,4.000000,3.300000,1.000000,0.100000,1.000000,1.000000,0.000000,0.000000,0.000000,1.000000
25%,1.000000,1.000000,5.289152e+05,37.800000,48.000000,20.000000,1.000000,1.000000,1.000000,1.000000,2.000000,3.000000,1.000000,1.000000,1.000000,2.000000,1.000000,3.000000,37.000000,6.600000,1.000000,2.000000,1.000000,1.000000,2111.750000,0.000000,0.000000,1.000000
50%,1.000000,1.000000,5.302990e+05,38.000000,60.000000,21.500000,3.000000,1.000000,3.000000,1.000000,3.000000,3.000000,2.000000,2.000000,1.000000,2.000000,3.000000,4.000000,43.000000,7.500000,2.000000,2.000000,1.000000,1.000000,3025.000000,0.000000,0.000000,2.000000
75%,2.000000,1.000000,5.347275e+05,38.400000,86.000000,35.000000,3.000000,3.000000,4.000000,2.000000,4.000000,4.000000,3.000000,2.000000,2.000000,2.000000,4.000000,5.000000,50.000000,54.000000,3.000000,2.000000,2.000000,2.000000,3209.000000,0.000000,0.000000,2.000000
max,2.000000,9.000000,5.305629e+06,40.800000,184.000000,96.000000,4.000000,4.000000,6.000000,3.000000,5.000000,4.000000,4.000000,3.000000,3.000000,8.500000,4.000000,5.000000,75.000000,89.000000,3.000000,10.100000,3.000000,2.000000,41110.000000,7111.000000,2209.000000,2.000000

In [97]:
df.to_excel('newmax.xlsx',sheet_name='Sheet_1')